# Generated by Django 6.0.2 on 2026-03-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, unique=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demirbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('seri_no', models.CharField(blank=True, max_length=100, null=True)),
                ('marka_model', models.CharField(blank=True, max_length=150, null=True)),
                ('satin_alma_tarihi', models.DateField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('stokta', 'Stokta'), ('zimmetli', 'Zimmetli'), ('arizali', 'Arızalı'), ('hurda', 'Hurda')], default='stokta', max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.birim')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150)),
                ('sicil_no', models.CharField(max_length=50, unique=True)),
                ('gorev', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.birim')),
            ],
        ),
    ]
