# Generated by Django 6.0.2 on 2026-03-03 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.birim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birim_bilgisi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
