# Generated by Django 6.0.2 on 2026-03-02 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZimmetKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verilme_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('iade_tarihi', models.DateField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('iade', 'İade Edildi')], default='aktif', max_length=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('demirbas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.demirbas')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.personel')),
            ],
        ),
    ]
